#!/bin/bash

SENSORS=($(sensors -u))
CONFIG="$1"

CPUDEV="k10temp-pci-00c3"
INTGPUDEV="amdgpu-pci-1200"
EXTGPUDEV="amdgpu-pci-0300"

TEMP=""
DEVICE=""

for((i=0; i<${#SENSORS[@]}; i++));
do
  case ${SENSORS[i]} in
    "${CPUDEV}")
      DEVICE="${CPUDEV}"
      ;;
    "${EXTGPUDEV}")
      DEVICE="${EXTGPUDEV}"
      ;;
    "${INTGPUDEV}")
      DEVICE="${INTGPUDEV}"
      ;;
    "temp2_input:")
      if [[ "${DEVICE}" == "${EXTGPUDEV}" ]]; then
        TEMP="${SENSORS[i+1]}"
      fi
      ;;
    *)
      ;;
  esac
done

GPUCOLOR=""
GPULOGO=""
if [[ $((${GPU%.*})) < 65 ]]; then
  GPUCOLOR="#0000CC"
  GPULOGO=""
elif [[ $((${GPU%.*})) > 85 ]]; then
  GPUCOLOR="#CC0000"
  GPULOGO=""
else
  GPULOGO=""
fi

if [[ ${CONFIG} == "i3bar" ]]; then
  echo "[{\"full text\":\"Ext GPU ${GPULOGO} ${TEMP%.*}°C\", \"color\":\"${GPUCOLOR}\"}],"
else
  echo "Ext GPU ${GPULOGO} ${TEMP%.*}°C"
fi
exit 0
