#!/bin/bash

SENSORS=($(sensors -u))
DIE1=""
DIE2=""

for((i=0; i<${#SENSORS[@]}; i++));
do
  case ${SENSORS[i]} in
    "temp3_input:")
      if [[ "$DIE1" == "" ]]; then
        DIE1="${SENSORS[i+1]}"
      fi
      ;;
    "temp4_input:")
      if [[ "$DIE2" == "" ]]; then
        DIE2="${SENSORS[i+1]}"
      fi
      ;;
    *)
      ;;
  esac
done

MAX=""
if [[ $((${DIE1%.*})) > $((${DIE2%.*})) ]]; then
  MAX=$DIE1
else
  MAX=$DIE2
fi
COLOR=""
if [[ $((${MAX%.*})) < 40 ]]; then
  COLOR="#0000CC"
elif [[ $((${MAX%.*})) > 80 ]]; then
  COLOR="#CC0000"
fi
echo "{\"full_text\":\" ${DIE1%.*}°C: ${DIE2%.*}°C\", \"color\":\"${COLOR}\"}"
exit 0
