# Monokai Pro (default "Pro" filter) — matches alacritty/waybar theming
# https://monokai.pro/

[main]
font=monospace:size=11
prompt="❯ "
layer=overlay

[border]
radius=8
width=2

[colors]
background=2d2a2eff
text=fcfcfaff
match=ff6188ff
selection=5b595cff
selection-text=fcfcfaff
selection-match=ff6188ff
border=ab9df2ff
